apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: prashantkushwaha121/helloworld
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /logs
          name: log-volume
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
      volumes:
      - name: log-volume
        emptyDir:
          sizeLimit: 500Mi
