name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the mainbranch

jobs:
  build-and-push:
    # Specify self-hosted runner
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java (if necessary for Maven build)
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'

    # Step 3: Build the Java project
    - name: Build Java Project
      working-directory: ./HelloWorld
      run: mvn clean package -DskipTests # Adjust for Gradle if needed

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build the Docker image
    - name: Build Docker Image
      working-directory: ./HelloWorld
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest .

    # Step 6: Push the Docker image to Docker Hub
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
